DROP DATABASE IF EXISTS kct9iean0roagv7b;
CREATE DATABASE kct9iean0roagv7b;
USE kct9iean0roagv7b;

CREATE TABLE note (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(30) NOT NULL,
  n_text VARCHAR(255) NOT NULL 
  
);

