DROP DATABASE IF EXISTS Note_Taker;
CREATE DATABASE Note_Taker;
USE Note_Taker;

CREATE TABLE note (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(30) NOT NULL
  n_text VARCHAR(255) NOT NULL,  
  
);

